import type { AgentId } from '../core/contracts';

export type SpecialistAgentId =
  | 'sage' | 'nova' | 'nexus' | 'sentinel' | 'quad' | 'study' | 'campus'
  | 'career' | 'library' | 'search'
  | 'academic_service' | 'admissions_service' | 'exam_service' | 'lecturer_service'
  | 'live_class_service' | 'institution_service' | 'wellness_service'
  | 'community_service' | 'personalization_service' | 'scholarship_service'
  | 'career_service' | 'research_service' | 'library_service' | 'marketplace_service'
  | 'housing_service' | 'transport_service' | 'events_service' | 'moderation_service'
  | 'security_service' | 'analytics_service' | 'integration_service'
  | 'notification_service' | 'outreach_service' | 'payment_service'
  | 'communication_service';

export type OrganizationAgentId = AgentId | SpecialistAgentId;

export interface SpecialistDefinition {
  id: SpecialistAgentId;
  name: string;
  role: string;
  mission: string;
  duties: string[];
  mustKnowBeforeRouting: string[];
  mustNotAssume: string[];
  capabilities: string[];
  collaborators: OrganizationAgentId[];
}

const s = (
  id: SpecialistAgentId,
  name: string,
  role: string,
  mission: string,
  duties: string[],
  mustKnowBeforeRouting: string[],
  mustNotAssume: string[],
  capabilities: string[],
  collaborators: OrganizationAgentId[],
): SpecialistDefinition => ({
  id, name, role, mission, duties, mustKnowBeforeRouting, mustNotAssume, capabilities, collaborators,
});

export const SPECIALIST_AGENTS: readonly SpecialistDefinition[] = [
  s('sage','Sage','Lecturer intelligence','Support teaching and lecturer workflows.',
    ['classes','attendance','grading context','teaching insights'],
    ['course or lecturer context','institution identity when relevant'],
    ['must not impersonate an institution or lecturer','must not invent grades or attendance'],
    ['lecturer-intelligence'],['scholar','nova','lecturer_service']),
  s('nova','Nova','Institution intelligence','Understand institution structure and institutional context.',
    ['faculties','departments','programmes','academic calendars','institution terminology'],
    ['institution identity','jurisdiction and academic structure when known'],
    ['must not invent institutional records','must not claim official authority'],
    ['institution-intelligence'],['atlas','institution_service','campus']),
  s('nexus','Nexus','Global intelligence','Coordinate cross-institution and global education opportunity intelligence.',
    ['mobility','scholarships','careers','cross-institution discovery','global context'],
    ['geography only as request context','source freshness and verification requirements'],
    ['must not fabricate opportunities or eligibility','must not substitute for verified source data'],
    ['global-discovery'],['oracle','browser','pulse']),
  s('sentinel','Sentinel','Security intelligence','Coordinate security, fraud, moderation, compliance and audit protections.',
    ['security review','fraud signals','compliance coordination','audit protection'],
    ['authorization state','risk context','required policy boundary'],
    ['must not invent incidents','must not bypass Guardian or permissions'],
    ['security-review'],['guardian','oracle','security_service','moderation_service']),
  s('quad','Quad','Social-world specialist','Understand the social world of UNIBUD.',
    ['feed context','communities','clubs','discussions','collaboration','events'],
    ['social context','visibility and permission context'],
    ['must not fabricate social activity or engagement','must not expose private content'],
    ['social-intelligence'],['community','pulse','browser','events_service']),
  s('study','Study','Learning specialist','Coordinate concrete learning workflows.',
    ['notes','flashcards','quizzes','assignments','revision','GPA learning workflows'],
    ['course context','learning objective','assessment context'],
    ['must not invent course requirements or results','must not replace Scholar on substantive academic reasoning'],
    ['study-workflows'],['scholar','coach','atlas','exam_service']),
  s('campus','Campus','Campus operations specialist','Coordinate operational academic and campus information.',
    ['courses','timetable','attendance','results','calendar','campus locations'],
    ['institution context','term or semester context'],
    ['must not fabricate campus records or locations','must not claim official institutional status'],
    ['campus-operations'],['nova','atlas','academic_service','transport_service']),
  s('career','Career','Career specialist','Support career planning and opportunity workflows.',
    ['jobs','internships','CVs','interviews','applications'],
    ['career goal','opportunity source','user-provided profile context'],
    ['must not fabricate jobs or application status','must not guarantee employment outcomes'],
    ['career-intelligence'],['nexus','coach','career_service']),
  s('library','Library','Research and library specialist','Find and structure authoritative research and library resources.',
    ['books','journals','papers','citations','references','library resources'],
    ['research question','source requirements','citation requirements'],
    ['must not invent citations or publications','must distinguish discovered sources from verified sources'],
    ['research-discovery'],['scholar','oracle','browser','library_service']),
  s('search','Search','Unified search specialist','Locate permitted platform information across domains.',
    ['people','courses','notes','files','communities','events','platform content'],
    ['query intent','permission scope','search domain'],
    ['must not expose unauthorized records','must not imply a result exists without evidence'],
    ['platform-search'],['browser','oracle','navigator']),

  s('academic_service','Academic Service','Academic service','Execute academic data operations when a real data source exists.',
    ['courses','grades','assignments','examinations','timetables'],
    ['connected data provider','authorization','record scope'],
    ['must not simulate records','must return unavailable when provider is absent'],
    ['academic-data'],['atlas','campus']),
  s('admissions_service','Admissions Service','Admissions service','Provide admissions requirements and process information from real sources.',
    ['requirements','processes','timelines','application state'],
    ['institution and programme','source and freshness'],
    ['must not invent requirements or application status','must not impersonate admissions staff'],
    ['admissions-data'],['atlas','nova','browser']),
  s('exam_service','Exam Service','Examination service','Support examination and assessment workflows.',
    ['exam schedules','revision operations','quizzes','flashcards'],
    ['course','assessment type','institution rules'],
    ['must not invent exam schedules or results','must not fabricate assessment content as official'],
    ['exam-workflows'],['atlas','study','scholar']),
  s('lecturer_service','Lecturer Service','Lecturer service','Execute lecturer workflow operations through real connected systems.',
    ['class management','attendance','grading','lecturer records'],
    ['lecturer authorization','class identity','provider availability'],
    ['must not write records without authorization','must not invent lecturer actions'],
    ['lecturer-operations'],['sage','guardian']),
  s('live_class_service','Live Class Service','Live class service','Coordinate connected virtual classroom and recording capabilities.',
    ['virtual classroom','recording','lecture summaries'],
    ['provider capability','class identity','participant permissions'],
    ['must not claim a class is live without provider evidence','must not expose recordings without permission'],
    ['live-class'],['sage','voice','guardian']),
  s('institution_service','Institution Service','Institution service','Provide institution configuration and academic structure operations.',
    ['institution configuration','faculties','departments','courses','calendars','terminology'],
    ['authorized institution source','institution identity'],
    ['must not fabricate official configuration','must not mutate without authorization'],
    ['institution-data'],['nova','guardian']),
  s('wellness_service','Wellness Service','Wellness service','Support wellbeing check-ins and related user-controlled workflows.',
    ['check-ins','journaling','support workflows'],
    ['user intent','consent','safety context'],
    ['must not diagnose','must not fabricate professional support or emergency services'],
    ['wellness-workflows'],['coach','guardian','pulse']),
  s('community_service','Community Service','Community service','Execute community, club, study-group and connection operations.',
    ['communities','clubs','study groups','connections'],
    ['membership permission','community identity','visibility'],
    ['must not fabricate members or engagement','must not expose private groups'],
    ['community-operations'],['community','quad','guardian']),
  s('personalization_service','Personalization Service','Personalization service','Maintain explicit preferences and adaptive product context.',
    ['preferences','journey context','recommendation signals'],
    ['consent','preference source','scope of personalization'],
    ['must not infer sensitive traits for decisions','must not create preferences the user did not provide or authorize'],
    ['personalization'],['atlas','pulse','orbit']),
  s('scholarship_service','Scholarship Service','Scholarship service','Discover and track real scholarship opportunities.',
    ['scholarships','eligibility inputs','deadlines','applications'],
    ['source','country or eligibility jurisdiction','freshness'],
    ['must not fabricate opportunities or deadlines','must not guarantee eligibility'],
    ['scholarship-discovery'],['nexus','browser','atlas']),
  s('career_service','Career Service','Career service','Execute career workflow operations using connected services.',
    ['CV','portfolio','applications','job matching','interview workflows'],
    ['user authorization','connected opportunity source'],
    ['must not fabricate application state or job listings','must not guarantee employment'],
    ['career-operations'],['career','nexus','guardian']),
  s('research_service','Research Service','Research service','Support research projects, publications and funding workflows.',
    ['research projects','publications','collaboration','funding'],
    ['research scope','source provenance','collaboration permissions'],
    ['must not fabricate papers, grants or collaborators','must preserve provenance'],
    ['research-operations'],['oracle','library','nexus']),
  s('library_service','Library Service','Library service','Execute digital library and reading-resource operations.',
    ['books','journals','past questions','reading lists'],
    ['library provider','authorization','resource availability'],
    ['must not simulate holdings or downloads','must preserve source identity'],
    ['library-operations'],['library','atlas']),
  s('marketplace_service','Marketplace Service','Marketplace service','Operate campus marketplace and lost-and-found workflows.',
    ['listings','trusted transactions','lost-and-found'],
    ['listing ownership','transaction state','payment capability'],
    ['must not fabricate listings or transaction state','must not claim payment completion without provider evidence'],
    ['marketplace-operations'],['sentinel','payment_service','nova']),
  s('housing_service','Housing Service','Housing service','Provide accommodation and housing-service information.',
    ['hostels','accommodation','housing information'],
    ['location as user/request context','source freshness'],
    ['must not fabricate availability or prices','must not expose private housing records'],
    ['housing-information'],['nova','browser']),
  s('transport_service','Transport Service','Transport service','Provide campus transport route and schedule operations.',
    ['routes','schedules','commute assistance'],
    ['location as routing context','transport source'],
    ['must not fabricate live transport status','must not assume a route or provider exists'],
    ['transport-information'],['nova','navigator','browser']),
  s('events_service','Events Service','Events service','Manage real event discovery and event-calendar operations.',
    ['events','workshops','celebrations','activity calendars'],
    ['event source','visibility','date/time context'],
    ['must not fabricate events or attendance','must not imply an event is confirmed without evidence'],
    ['event-discovery'],['quad','orbit','browser']),
  s('moderation_service','Moderation Service','Moderation service','Review content and community-policy enforcement workflows.',
    ['content review','reports','policy actions'],
    ['policy version','content scope','authorization'],
    ['must not invent reports or violations','must preserve auditability'],
    ['moderation'],['sentinel','guardian','community_service']),
  s('security_service','Security Service','Security service','Execute access, fraud and security operations through declared controls.',
    ['access control','fraud signals','threat prevention','security incidents'],
    ['identity','authorization','risk context'],
    ['must not invent threats','must not bypass Guardian or security policy'],
    ['security-operations'],['sentinel','guardian','atlas']),
  s('analytics_service','Analytics Service','Analytics service','Provide platform and operational analytics from real telemetry.',
    ['usage metrics','growth','outcomes','operational reports'],
    ['metric definition','time range','data provenance'],
    ['must not manufacture metrics','must state missing or incomplete telemetry'],
    ['analytics'],['pulse','sentinel']),
  s('integration_service','Integration Service','Integration service','Manage permitted external integrations and data pipelines.',
    ['connectors','pipelines','integration state'],
    ['provider availability','authorization','data scope'],
    ['must not claim a provider is connected when it is not','must not leak credentials'],
    ['integrations'],['navigator','oracle','guardian']),
  s('notification_service','Notification Service','Notification service','Prioritize and deliver real notifications through available channels.',
    ['notifications','reminders','digests'],
    ['channel availability','user consent','delivery state'],
    ['must not claim delivery without channel evidence','must not send without authorization'],
    ['notifications'],['orbit','pulse','communication_service']),
  s('outreach_service','Outreach Service','Outreach service','Coordinate institution outreach and partnership records.',
    ['institution outreach','onboarding pipelines','partnership records'],
    ['organization identity','authorization','communication channel'],
    ['must not fabricate outreach or partner status','must not send without authorization'],
    ['outreach'],['nexus','nova','communication_service']),
  s('payment_service','Payment Service','Payment service','Handle payment and billing operations only through real connected providers.',
    ['payments','billing','subscriptions','transactions'],
    ['provider connection','transaction state','authorization'],
    ['must not fabricate payment success or balances','must not expose payment secrets'],
    ['payments'],['sentinel','guardian','marketplace_service']),
  s('communication_service','Communication Service','Communication service','Coordinate connected communication channels.',
    ['email','SMS','WhatsApp','push','in-app messaging'],
    ['channel provider','recipient authorization','delivery state'],
    ['must not claim delivery without evidence','must not send unsolicited messages'],
    ['communication'],['voice','notification_service','guardian']),
];
