import type { AgentId } from './contracts';

export interface ExtendedAgentDefinition {
  id: AgentId; role: string; responsibility: string; contextScope: string[]; memoryScope: string[]; permissions: string[]; collaborators: AgentId[];
}

/**
 * Canonical extended UNIBUD intelligence catalog.
 *
 * These are internal capability roles, not 37 additional user-facing assistants.
 * The runtime may execute them only when the required capability/provider exists.
 * No unavailable capability is simulated.
 */
export const EXTENDED_AGENT_DEFINITIONS: ExtendedAgentDefinition[] = [
  { id: "architect", role: "system architect", responsibility: "Own system structure, module boundaries, integrations and technical solution design.", contextScope: ["architecture", "modules", "integrations"], memoryScope: ["architecture-state"], permissions: ["architect"], collaborators: ["oracle", "spark"] },
  { id: "artist", role: "visual creative specialist", responsibility: "Shape visual language, visual assets and creative direction when a visual task requires it.", contextScope: ["visual-design", "brand", "creative"], memoryScope: ["creative-context"], permissions: ["visual-create"], collaborators: ["creator", "vision"] },
  { id: "sage", role: "lecturer intelligence", responsibility: "Support teaching workflows, classes, attendance, grading and lecturer-facing insights.", contextScope: ["lecturer", "classes", "teaching"], memoryScope: ["lecturer-context"], permissions: ["lecturer-read"], collaborators: ["spark", "scholar"] },
  { id: "nova", role: "institution intelligence", responsibility: "Manage institution structure, academic calendars, terminology and institutional data.", contextScope: ["institution", "faculty", "department", "programme"], memoryScope: ["institution-context"], permissions: ["institution-read"], collaborators: ["spark", "atlas"] },
  { id: "nexus", role: "global intelligence", responsibility: "Handle cross-institution discovery, mobility, scholarships, careers and global education context.", contextScope: ["global", "opportunities", "mobility"], memoryScope: ["global-context"], permissions: ["global-read"], collaborators: ["oracle", "pulse"] },
  { id: "sentinel", role: "security intelligence", responsibility: "Coordinate security, moderation, fraud, compliance and audit protections.", contextScope: ["security", "compliance", "moderation"], memoryScope: ["security-state"], permissions: ["security-review"], collaborators: ["guardian", "oracle"] },
  { id: "quad", role: "social-world specialist", responsibility: "Handle the social world: feed, communities, clubs, discussions, collaboration and events.", contextScope: ["quad", "social", "community", "events"], memoryScope: ["social-context"], permissions: ["social-read"], collaborators: ["community", "pulse"] },
  { id: "study", role: "learning specialist", responsibility: "Handle notes, flashcards, quizzes, assignments, research, revision and GPA learning workflows.", contextScope: ["study", "courses", "assignments", "revision"], memoryScope: ["learning"], permissions: ["study-read"], collaborators: ["scholar", "coach", "atlas"] },
  { id: "campus", role: "campus operations specialist", responsibility: "Handle faculties, departments, courses, timetable, attendance, results, calendar and campus locations.", contextScope: ["campus", "courses", "timetable", "calendar"], memoryScope: ["campus-context"], permissions: ["campus-read"], collaborators: ["nova", "atlas"] },
  { id: "career", role: "career specialist", responsibility: "Handle jobs, internships, CVs, interviews, applications and career opportunities.", contextScope: ["career", "jobs", "internships", "applications"], memoryScope: ["career-context"], permissions: ["career-read"], collaborators: ["nexus", "coach"] },
  { id: "library", role: "research and library specialist", responsibility: "Find authoritative books, journals, papers, citations, references and library resources.", contextScope: ["library", "research", "citations"], memoryScope: ["research-context"], permissions: ["library-read"], collaborators: ["scholar", "oracle"] },
  { id: "search", role: "unified search specialist", responsibility: "Find relevant people, courses, notes, files, communities, events and other permitted platform content.", contextScope: ["search", "platform", "discovery"], memoryScope: ["search-history"], permissions: ["search"], collaborators: ["oracle", "navigator"] },

  { id: "academic_service", role: "academic service", responsibility: "Provide course, grade, assignment, examination and timetable operations.", contextScope: ["academics", "assignments", "examinations", "timetable"], memoryScope: ["academic-state"], permissions: ["academic-service"], collaborators: ["atlas"] },
  { id: "admissions_service", role: "admissions service", responsibility: "Handle admission requirements, processes and timelines.", contextScope: ["admissions", "requirements"], memoryScope: ["admissions-state"], permissions: ["admissions-service"], collaborators: ["atlas"] },
  { id: "exam_service", role: "examination service", responsibility: "Handle exam scheduling, revision support, quizzes and flashcard operations.", contextScope: ["examinations", "revision", "assessment"], memoryScope: ["exam-state"], permissions: ["exam-service"], collaborators: ["atlas", "study"] },
  { id: "lecturer_service", role: "lecturer service", responsibility: "Provide lecturer workflow, class management, attendance and grading operations.", contextScope: ["lecturer", "classes", "attendance", "grades"], memoryScope: ["lecturer-state"], permissions: ["lecturer-service"], collaborators: ["sage"] },
  { id: "live_class_service", role: "live class service", responsibility: "Coordinate virtual classroom, recording and lecture-summary capabilities when connected.", contextScope: ["live-class", "recordings"], memoryScope: ["live-class-state"], permissions: ["live-class-service"], collaborators: ["sage"] },
  { id: "institution_service", role: "institution service", responsibility: "Provide institution configuration, academic structures, calendars and terminology.", contextScope: ["institution", "faculties", "departments", "courses"], memoryScope: ["institution-state"], permissions: ["institution-service"], collaborators: ["nova"] },
  { id: "wellness_service", role: "wellness service", responsibility: "Handle wellbeing check-ins, mood context, journaling and support workflows.", contextScope: ["wellbeing", "support"], memoryScope: ["wellbeing-state"], permissions: ["wellness-service"], collaborators: ["pulse", "guardian"] },
  { id: "community_service", role: "community service", responsibility: "Manage community, club, study-group and connection capabilities.", contextScope: ["communities", "clubs", "connect", "study-groups"], memoryScope: ["community-state"], permissions: ["community-service"], collaborators: ["pulse", "community"] },
  { id: "personalization_service", role: "personalization service", responsibility: "Maintain preference learning and adaptive recommendations across the student's journey.", contextScope: ["personalization", "preferences", "journey"], memoryScope: ["preferences", "journey"], permissions: ["personalize"], collaborators: ["pulse", "atlas"] },
  { id: "scholarship_service", role: "scholarship service", responsibility: "Discover scholarships, evaluate eligibility and track applications using real data.", contextScope: ["scholarships", "opportunities", "eligibility"], memoryScope: ["opportunity-state"], permissions: ["scholarship-service"], collaborators: ["nexus"] },
  { id: "career_service", role: "career service", responsibility: "Provide career coaching, CV, portfolio, interview and job-matching operations.", contextScope: ["career", "cv", "portfolio", "jobs"], memoryScope: ["career-state"], permissions: ["career-service"], collaborators: ["nexus", "career"] },
  { id: "research_service", role: "research service", responsibility: "Support research projects, publications, collaboration and funding workflows.", contextScope: ["research", "publications", "funding"], memoryScope: ["research-state"], permissions: ["research-service"], collaborators: ["nexus", "library"] },
  { id: "library_service", role: "library service", responsibility: "Provide digital library, books, journals, past questions and reading-list operations.", contextScope: ["library", "books", "journals"], memoryScope: ["library-state"], permissions: ["library-service"], collaborators: ["atlas", "library"] },
  { id: "marketplace_service", role: "marketplace service", responsibility: "Handle campus marketplace listings, trusted transactions and lost-and-found workflows.", contextScope: ["marketplace", "commerce", "lost-found"], memoryScope: ["marketplace-state"], permissions: ["marketplace-service"], collaborators: ["nova", "sentinel"] },
  { id: "housing_service", role: "housing service", responsibility: "Handle accommodation, hostel and housing-service information.", contextScope: ["housing", "accommodation"], memoryScope: ["housing-state"], permissions: ["housing-service"], collaborators: ["nova"] },
  { id: "transport_service", role: "transport service", responsibility: "Handle campus transport routes, schedules and commute assistance.", contextScope: ["transport", "routes", "schedules"], memoryScope: ["transport-state"], permissions: ["transport-service"], collaborators: ["nova", "navigator"] },
  { id: "events_service", role: "events service", responsibility: "Handle campus events, workshops, celebrations and activity calendars.", contextScope: ["events", "calendar", "activities"], memoryScope: ["events-state"], permissions: ["events-service"], collaborators: ["pulse", "quad"] },
  { id: "moderation_service", role: "moderation service", responsibility: "Review content, reports and community-policy enforcement actions.", contextScope: ["moderation", "reports", "policy"], memoryScope: ["moderation-state"], permissions: ["moderation-service"], collaborators: ["sentinel", "guardian"] },
  { id: "security_service", role: "security service", responsibility: "Handle access control, fraud signals, threat prevention and security incidents.", contextScope: ["security", "fraud", "access"], memoryScope: ["security-state"], permissions: ["security-service"], collaborators: ["sentinel", "guardian"] },
  { id: "analytics_service", role: "analytics service", responsibility: "Provide platform usage, growth, outcomes and operational analytics.", contextScope: ["analytics", "metrics", "reports"], memoryScope: ["analytics-state"], permissions: ["analytics-service"], collaborators: ["sentinel", "pulse"] },
  { id: "integration_service", role: "integration service", responsibility: "Manage permitted external integrations, connectors and data pipelines.", contextScope: ["integrations", "connectors", "pipelines"], memoryScope: ["integration-state"], permissions: ["integration-service"], collaborators: ["sentinel", "oracle"] },
  { id: "notification_service", role: "notification service", responsibility: "Prioritize and deliver real notifications, reminders and digests when channels exist.", contextScope: ["notifications", "reminders", "digests"], memoryScope: ["notification-state"], permissions: ["notification-service"], collaborators: ["pulse", "orbit"] },
  { id: "outreach_service", role: "outreach service", responsibility: "Handle institution outreach, onboarding pipelines and partnership records.", contextScope: ["outreach", "institutions", "partnerships"], memoryScope: ["outreach-state"], permissions: ["outreach-service"], collaborators: ["nexus", "nova"] },
  { id: "payment_service", role: "payment service", responsibility: "Handle payment, billing, subscriptions and transaction oversight only when a real provider is connected.", contextScope: ["payments", "billing", "transactions"], memoryScope: ["payment-state"], permissions: ["payment-service"], collaborators: ["sentinel", "marketplace_service"] },
  { id: "communication_service", role: "communication service", responsibility: "Coordinate email, SMS, WhatsApp, push and in-app messaging channels when connected.", contextScope: ["communication", "messaging", "channels"], memoryScope: ["communication-state"], permissions: ["communication-service"], collaborators: ["pulse", "voice", "notification_service"] },
];
